/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ccsds_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9d7df0e4206f192e5e24ce5f4311fac0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/ccsds_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <ccsds_encoder_pydoc.h>

void bind_ccsds_encoder(py::module& m)
{

    using ccsds_encoder    = ::gr::ccsds::ccsds_encoder;


    py::class_<ccsds_encoder, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<ccsds_encoder>>(m, "ccsds_encoder", D(ccsds_encoder))

        .def(py::init(&ccsds_encoder::make),
           py::arg("itemsize") = 0,
           py::arg("len_tag_key") = "packet_len",
           py::arg("rs_encode") = true,
           py::arg("interleave") = true,
           py::arg("scramble") = true,
           py::arg("printing") = false,
           py::arg("verbose") = false,
           py::arg("n_interleave") = 5,
           py::arg("dual_basis") = true,
           D(ccsds_encoder,make)
        )
        




        
        .def("num_frames",&ccsds_encoder::num_frames,       
            D(ccsds_encoder,num_frames)
        )

        ;




}








